# Generated by Django 5.2.3 on 2025-09-05 20:06

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2401e2d5-58c6-4b1e-bad3-f268ff477b50'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='codeverified',
            name='verify_type',
            field=models.CharField(choices=[('via_email', 'Via Email'), ('via_phone', 'Via Phone')], max_length=31),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='auth_status',
            field=models.CharField(choices=[('new', 'New'), ('code_verified', 'Code Verified'), ('done', 'Done'), ('photo_done', 'Photo Done')], default='new', max_length=31),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='auth_type',
            field=models.CharField(choices=[('via_email', 'Via Email'), ('via_phone', 'Via Phone')], max_length=31),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2401e2d5-58c6-4b1e-bad3-f268ff477b50'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users_photo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('ordinary_user', 'Ordinary User'), ('manager', 'Manager'), ('admin', 'Admin')], default='ordinary_user', max_length=31),
        ),
    ]
