# Generated by Django 5.2.3 on 2025-09-08 10:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_codeverified_id_alter_codeverified_verify_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ed90b812-e52c-49e3-a4e3-71250fae4e54'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ed90b812-e52c-49e3-a4e3-71250fae4e54'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
