# Generated by Django 5.2.3 on 2025-09-09 10:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_codeverified_id_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('44bbfae5-f1d1-4fd5-85f5-673ff993860c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('44bbfae5-f1d1-4fd5-85f5-673ff993860c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
