# Generated by Django 5.2.3 on 2025-09-11 08:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_codeverified_id_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4abc7862-f035-49b7-8e93-05d511053967'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='codeverified',
            name='verify_type',
            field=models.CharField(choices=[('via_phone', 'Via Phone')], max_length=31),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='auth_type',
            field=models.CharField(choices=[('via_phone', 'Via Phone')], max_length=31),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4abc7862-f035-49b7-8e93-05d511053967'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
