# Generated by Django 5.2.3 on 2025-09-12 18:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_codeverified_id_alter_codeverified_verify_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('93c8e3c1-b110-476b-8936-cae50abf0604'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('93c8e3c1-b110-476b-8936-cae50abf0604'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
