# Generated by Django 5.2.3 on 2025-09-15 10:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_codeverified_id_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dc090b6c-a2ca-474d-9433-784d8315dad6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dc090b6c-a2ca-474d-9433-784d8315dad6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
